import Foundation
import CoreML

/// On-Device Card Type Classification Service (Consumes 384-d vector -> Predicts Card Type)
public final class CardTypeClassifierService {

    private let model: MLModel?

    public init() {
        let config = MLModelConfiguration()
        // Hardware Acceleration: Route directly to Apple Neural Engine (ANE)
        config.computeUnits = .all

        do {
            // `RiftboundCardTypeClassifier.mlpackage` is bundled via
            // `.copy` (not `.process` - see `Package.swift`'s doc comment
            // on why), so there's no auto-generated wrapper type; compile
            // and load it directly instead.
            guard let packageURL = Bundle.module.url(forResource: "RiftboundCardTypeClassifier", withExtension: "mlpackage") else {
                throw CocoaError(.fileNoSuchFile)
            }
            let compiledURL = try MLModel.compileModel(at: packageURL)
            self.model = try MLModel(contentsOf: compiledURL, configuration: config)
            print("✅ RiftboundCardTypeClassifier loaded successfully on Neural Engine!")
        } catch {
            print("❌ Failed to load RiftboundCardTypeClassifier.mlpackage: \(error)")
            self.model = nil
        }
    }

    /// Classifies a 384-dimensional embedding vector into a card type label
    /// - Parameter embedding: Array of 384 Float values generated by MiniLMEmbedderService
    /// - Returns: Tuple containing predicted `cardType` (String) and `confidence` (Double)
    public func classify(embedding: [Float]) -> (cardType: String, confidence: Double)? {
        guard let model = model else { return nil }

        guard embedding.count == 384 else {
            print("⚠️ Dimension error: expected 384 floats, received \(embedding.count)")
            return nil
        }

        do {
            // 1. Construct MLMultiArray tensor of shape [1, 384]
            let inputMultiArray = try MLMultiArray(shape: [1, 384], dataType: .float32)

            for (index, value) in embedding.enumerated() {
                inputMultiArray[index] = NSNumber(value: value)
            }

            // 2. Perform on-device Core ML inference
            let inputs = try MLDictionaryFeatureProvider(dictionary: ["plain_text_embedding": inputMultiArray])
            let output = try model.prediction(from: inputs)

            // 3. Extract predicted class label and confidence probability using PyTorch CoreML property names
            guard let predictedLabel = output.featureValue(for: "classLabel")?.stringValue else {
                print("❌ Core ML Classification Error: no 'classLabel' output feature")
                return nil
            }
            let probs = output.featureValue(for: "classLabel_probs")?.dictionaryValue ?? [:]
            let confidence = probs[predictedLabel]?.doubleValue ?? 0.0

            return (cardType: predictedLabel, confidence: confidence)

        } catch {
            print("❌ Core ML Classification Error: \(error)")
            return nil
        }
    }
}
