import Foundation
import CoreML

/// On-Device Card Type Classification Service (Consumes 384-d vector -> Predicts Card Type)
public final class CardTypeClassifierService {
    
    private let model: RiftboundCardTypeClassifier?
    
    public init() {
        let config = MLModelConfiguration()
        // Hardware Acceleration: Route directly to Apple Neural Engine (ANE)
        config.computeUnits = .all
        
        do {
            self.model = try RiftboundCardTypeClassifier(configuration: config)
            print("✅ RiftboundCardTypeClassifier loaded successfully on Neural Engine!")
        } catch {
            print("❌ Failed to load RiftboundCardTypeClassifier.mlpackage: \(error)")
            self.model = nil
        }
    }
    
    /// Classifies a 384-dimensional embedding vector into a card type label
    /// - Parameter embedding: Array of 384 Float values generated by MiniLMEmbedderService
    /// - Returns: Tuple containing predicted `cardType` (String) and `confidence` (Double)
    public func classify(embedding: [Float]) -> (cardType: String, confidence: Double)? {
        guard let model = model else { return nil }
        
        guard embedding.count == 384 else {
            print("⚠️ Dimension error: expected 384 floats, received \(embedding.count)")
            return nil
        }
        
        do {
            // 1. Construct MLMultiArray tensor of shape [1, 384]
            let inputMultiArray = try MLMultiArray(shape: [1, 384], dataType: .float32)
            
            for (index, value) in embedding.enumerated() {
                inputMultiArray[index] = NSNumber(value: value)
            }
            
            // 2. Perform on-device Core ML inference
            let output = try model.prediction(plain_text_embedding: inputMultiArray)
            
            // 3. Extract predicted class label and confidence probability using PyTorch CoreML property names
            let predictedLabel = output.classLabel
            let confidence = output.classLabel_probs[predictedLabel] ?? 0.0
            
            return (cardType: predictedLabel, confidence: confidence)
            
        } catch {
            print("❌ Core ML Classification Error: \(error)")
            return nil
        }
    }
}
