//
//  File.swift
//  RiftboundTextProcessing
//
//  Created by I Gusti Ngurah Bagus Ferry Mahayudha on 11/08/26.
//

import Foundation
import SwiftData

/// SwiftData persistent entity for a tagged card.
///
/// Kept as a plain `@Model` (not `@Generable`): the two macros don't compose,
/// so the Foundation Model's structured-output target lives in the separate
/// `TaggedCardResult` struct below, which is mapped into this entity for
/// persistence.
@Model
public final class RiftboundCard: @unchecked Sendable {
    @Attribute(.unique) public var cardID: String
    public var cleanName: String
    public var rawText: String

    // Structured properties generated by the Foundation Model
    public var cardType: String // "Unit" | "Spell" | "Rune" | "Battlefield" | "Legend"
    public var energyCost: Int
    public var extractedTags: [String]
    public var categories: [String]

    public init(
        cardID: String = UUID().uuidString,
        cleanName: String = "",
        rawText: String = "",
        cardType: String = "Unknown",
        energyCost: Int = 0,
        extractedTags: [String] = [],
        categories: [String] = []
    ) {
        self.cardID = cardID
        self.cleanName = cleanName
        self.rawText = rawText
        self.cardType = cardType
        self.energyCost = energyCost
        self.extractedTags = extractedTags
        self.categories = categories
    }
}
